apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  destination:
    namespace: sonarr
    server: https://kubernetes.default.svc
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: sonarr
    targetRevision: 16.3.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true