apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: danas.hangar.bpfx.org
    path: /volume1/dataz/Media/Movies