apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
spec:
  project: default
  destination:
    namespace: heimdall
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/travismontana/ttl-ops
    path: helm/pirateapps
    targetRevision: main
    helm:
      parameters:
      - name: name
        value: heimdall
      - name: port
        value: "80"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true