apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies-nfs
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: plex-movies-nfs