apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/travismontana/ttl-ops
    targetRevision: main
    path: apgroups/pirate/arr-app
    helm:
      valueFiles:
        - values/sonarr.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true