---
kind: pipeline
type: docker
name: tofu-k3s

steps:
  - name: buildvms
    image: ghcr.io/opentofu/opentofu:latest
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
      token: 
        from_secret: proxmoxToken
    commands:
      - cd IaC/lab/code
      - tofu init
      - tofu plan -var "clusterfile=$CLUSTERS_FILE"

trigger:
  event:
    - custom

---
kind: pipeline
type: docker
name: ansible-k3s

steps:
  - name: install-k3s
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
    commands:
      - pip install ansible
      - cd IaC/ansible
      - ansible-playbook k3s_main.yaml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom

---
kind: pipeline
type: docker
name: ansible-argo

steps:
  - name: install-argo
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
    commands:
      - pip install ansible
      - cd IaC/ansible
      - ansible-playbook k3s_initial_appload.yaml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom

---
kind: pipeline
type: docker
name: ansible-apps

steps:
  - name: install-apps
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
    commands:
      - pip install ansible
      - cd IaC/ansible
      - ansible-playbook 03-cluster-apps.yml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom