---
kind: pipeline
type: docker
name: tofu-k3s

steps:
  - name: buildvms
    image: ghcr.io/opentofu/opentofu:latest
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
      PROMOXTOKEN: 
        from_secret: proxmoxToken
      SSHPRIVKEY: 
        from_secret: sshPrivateKey
      SSHPUBKEY: 
        from_secret: sshPublicKey
      AWS_REGION:
        from_secret: aws_region
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWSVALS:
        from_secret: awsVals
    commands:
      - cd IaC/lab/code
      - tofu init
      - tofu plan -var "clusterfile=$CLUSTERS_FILE" -var "token=$PROMOXTOKEN" -var "ssh_public_key=$SSHPUBKEY" -var "ssh_private_key=$SSHPRIVKEY" -var "aws_credentials=$AWSVALS"
      - eval $(ssh-agent -s)
      - echo "${SSHPRIVKEY}" | ssh-add -
      - tofu apply -auto-approve -var "clusterfile=$CLUSTERS_FILE" -var "token=$PROMOXTOKEN" -var "ssh_public_key=$SSHPUBKEY" -var "ssh_private_key=$SSHPRIVKEY" -var "aws_credentials=$AWSVALS"


trigger:
  event:
    - custom

---
kind: pipeline
type: docker
name: ansible-k3s

depends_on:
  - tofu-k3s

steps:
  - name: install-k3s
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
    commands:
      - pip install ansible
      - cd IaC/ansible
      - ansible-playbook k3s_main.yaml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom

---
kind: pipeline
type: docker
name: ansible-argo

depends_on:
  - ansible-k3s

steps:
  - name: install-argo
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
    commands:
      - pip install ansible
      - cd IaC/ansible
      - ansible-playbook k3s_initial_appload.yaml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom

---
kind: pipeline
type: docker
name: ansible-apps

depends_on:
  - ansible-argo

steps:
  - name: install-apps
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
    commands:
      - pip install ansible
      - cd IaC/ansible
      - ansible-playbook 03-cluster-apps.yml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom