---
kind: pipeline
type: docker
name: tofu-destroy

steps:
  - name: destroy-vms
    image: ghcr.io/opentofu/opentofu:latest
    volumes:
      - name: terraform-cache
        path: /terraform
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
      PROMOXTOKEN: 
        from_secret: proxmoxToken
      SSHPRIVKEY: 
        from_secret: sshPrivateKey
      SSHPUBKEY: 
        from_secret: sshPublicKey
      AWS_REGION:
        from_secret: aws_region
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWSVALS:
        from_secret: awsVals   
      TF_PLUGIN_CACHE_DIR: /terraform
      DELETE: ${DELETE}
    commands:
      - cd IaC/lab/code
      - sh -c 'if [ "$DELETE" = "true" ]; then echo "DELETE=true, destroying..."; cd IaC/lab/code; tofu init; tofu destroy -auto-approve -var "clusterfile=$CLUSTERS_FILE" -var "token=$PROMOXTOKEN" -var "ssh_public_key=$SSHPUBKEY" -var "ssh_private_key=$SSHPRIVKEY" -var "aws_credentials=$AWSVALS"; fi'
trigger:
  event:
    - custom

volumes:
  - name: terraform-cache
    host:
      path: /terraform

---
kind: pipeline
type: docker
name: tofu-k3s

steps:
  - name: buildvms
    image: ghcr.io/opentofu/opentofu:latest
    volumes:
      - name: terraform-cache
        path: /terraform
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
      PROMOXTOKEN: 
        from_secret: proxmoxToken
      SSHPRIVKEY: 
        from_secret: sshPrivateKey
      SSHPUBKEY: 
        from_secret: sshPublicKey
      AWS_REGION:
        from_secret: aws_region
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWSVALS:
        from_secret: awsVals   
      TF_PLUGIN_CACHE_DIR: /terraform
      DELETE: ${DELETE} 
    commands:
      - sh -c 'if [ "$DELETE" = "true" ]; then echo "DELETE=true, skipping ansible-k3s..."; exit 0; fi' 
      - cd IaC/lab/code
      - tofu init
      - tofu plan -var "clusterfile=$CLUSTERS_FILE" -var "token=$PROMOXTOKEN" -var "ssh_public_key=$SSHPUBKEY" -var "ssh_private_key=$SSHPRIVKEY" -var "aws_credentials=$AWSVALS"
      - eval $(ssh-agent -s)
      - echo "$SSHPRIVKEY" > /tmp/id_ed25519
      - chmod 600 /tmp/id_ed25519
      - ssh-add /tmp/id_ed25519
      - tofu apply -auto-approve -var "clusterfile=$CLUSTERS_FILE" -var "token=$PROMOXTOKEN" -var "ssh_public_key=$SSHPUBKEY" -var "ssh_private_key=$SSHPRIVKEY" -var "aws_credentials=$AWSVALS"
      - sleep 5
      - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null pi@172.16.2.23 "pihole restartdns reload"
      - echo "Flushed dns on pihole"
      - sleep 5


trigger:
  event:
    - custom

volumes:
  - name: terraform-cache
    host:
      path: /terraform

---
kind: pipeline
type: docker
name: ansible-k3s

depends_on:
  - tofu-k3s

steps:
  - name: install-k3s
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
      PIP_CACHE_DIR: /pip-cache
      SSHPRIVKEY: 
        from_secret: sshPrivateKey
      DELETE: ${DELETE} 
    commands:
      - sh -c 'if [ "$DELETE" = "true" ]; then echo "DELETE=true, skipping ansible-k3s..."; exit 0; fi' 
      - pip install ansible
      - cd IaC/ansible
      - eval $(ssh-agent -s)
      - echo "$SSHPRIVKEY" > /tmp/id_ed25519
      - chmod 600 /tmp/id_ed25519
      - ssh-add /tmp/id_ed25519
      - ansible-playbook k3s_main.yaml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom

volumes:
  - name: pip-cache
    host:
      path: /pip

---
kind: pipeline
type: docker
name: ansible-argo

depends_on:
  - ansible-k3s

steps:
  - name: install-argo
    image: python:3.11
    volumes:
      - name: pip-cache
        path: /pip-cache
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
      PIP_CACHE_DIR: /pip-cache
      SSHPRIVKEY: 
        from_secret: sshPrivateKey
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_REGION:
        from_secret: aws_region
      SSHPRIVKEY: 
        from_secret: sshPrivateKey
      DELETE: ${DELETE} 
    commands:
      - sh -c 'if [ "$DELETE" = "true" ]; then echo "DELETE=true, skipping ansible-k3s..."; exit 0; fi' 
      - pip install ansible
      - cd IaC/ansible
      - eval $(ssh-agent -s)
      - echo "$SSHPRIVKEY" > /tmp/id_ed25519
      - chmod 600 /tmp/id_ed25519
      - ssh-add /tmp/id_ed25519
      - ansible-playbook k3s_initial_appload.yaml -e "clusters_file=$CLUSTERS_FILE" -e "aws_access_key=$AWS_ACCESS_KEY_ID" -e "aws_secret_key=$AWS_SECRET_ACCESS_KEY"

trigger:
  event:
    - custom

volumes:
  - name: pip-cache
    host:
      path: /pip

---
kind: pipeline
type: docker
name: ansible-apps

depends_on:
  - ansible-argo

steps:
  - name: install-apps
    image: python:3.11
    environment:
      CLUSTERS_FILE: /drone/src/platforms/clusters.json
      PIP_CACHE_DIR: /pip-cache
      SSHPRIVKEY: 
        from_secret: sshPrivateKey
      DELETE: ${DELETE}
    commands:
      - sh -c 'if [ "$DELETE" = "true" ]; then echo "DELETE=true, skipping ansible-k3s..."; exit 0; fi' 
      - #pip install ansible
      - cd IaC/ansible
      - eval $(ssh-agent -s)
      - echo "$SSHPRIVKEY" > /tmp/id_ed25519
      - chmod 600 /tmp/id_ed25519
      - ssh-add /tmp/id_ed25519
      - echo "Done"
      #- ansible-playbook 03-cluster-apps.yml -e "clusters_file=$CLUSTERS_FILE"

trigger:
  event:
    - custom

volumes:
  - name: pip-cache
    host:
      path: /pip


