apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default
  destination:
    namespace: prowlarr
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/travismontana/ttl-ops
    path: helm/pirateapps
    targetRevision: main
    helm:
      parameters:
      - name: name
        value: prowlarr
      - name: port
        value: "9696"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true