apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oteloperator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: oteloperator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-operator
    targetRevision: 0.99.0
    helm:
      parameters:
      - name: manager.autoInstrumentation.go.enabled
        value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true