apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/travismontana/ttl-ops
          revision: HEAD
          files:
          - path: appgroups/core/*.yaml
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      destination:
        server: '{{.server}}'
        namespace: core
      sources:
        - repoURL: https://github.com/travismontana/ttl-ops
          targetRevision: HEAD
          ref: values
        - chart: '{{.chart}}'
          repoURL: '{{.repoUrl}}'
          targetRevision: '{{.version}}'
          helm:
            releaseName: '{{.releaseName}}'
            valueFiles:
              - $values/appgroups/core/{{.name}}/values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true