apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/travismontana/ttl-ops
          revision: HEAD
          files:
          - path: appgroups/core/core.yaml
      - list:
          elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: default
      syncPolicy:
        automated:
          selfHeal: true    
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true     
      sources:
        - chart: '{{.chart}}'
          repoURL: '{{.repoUrl}}'
          targetRevision: '{{.version}}'
          helm:
            releaseName: '{{.releaseName}}'
            valueFiles:
              - ../{{.name}}/values.yaml
            parameters:
{{- range .parameters }}
              - name: {{ .name }}
                value: "{{ .value }}"
{{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'