apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/travismontana/ttl-ops
          revision: HEAD
          directories:
          - path: appgroups/core/*
  template:
    metadata:
      name: '{{.name}}-{{.path.basename}}'
    spec:
      project: default
      destination:
        namespace: '{{.path.basename}}'
        server: '{{.server}}'
      source:
        repoURL: https://github.com/travismontana/ttl-ops
        targetRevision: HEAD
        path: 'appgroups/core/{{.path.basename}}'
        helm:
          parameters:
            - name: clusterName
              value: '{{.name}}'
            - name: kubernetes-dashboard.app.ingress.hosts[0].host
              value: '{{.name}}.abode.tailandtraillabs.org'
            - name: kubernetes-dashboard.app.ingress.tls.hosts[0]
              value: '{{.name}}.abode.tailandtraillabs.org'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true