apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/travismontana/ttl-ops
          revision: HEAD
          files:
          - path: appgroups/core/core.yaml
  template:
    metadata:
      name: '{{ index .key.name }}-{{ index .metadata.labels "cluster-name" }}'
    spec:
      project: default
      destination:
        namespace: '{{ index .key.namespace }}'
        server: '{{.server}}'
      source:
        repoURL: '{{ index .key.repoUrl }}'
        chart: '{{ index .key.chart }}'
        targetRevision: '{{ index .key.version }}'
        helm:
          releaseName: '{{ index .key.releaseName }}'
          valueFiles:
            - $values/appgroups/core/{{ index .key.name }}/values.yaml
          parameters:
            - name: clusterName
              value: '{{ index .metadata.labels "cluster-name" }}'
      sources:
        - repoURL: https://github.com/travismontana/ttl-ops
          targetRevision: HEAD
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true