apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/travismontana/ttl-ops
          revision: HEAD
          directories:
          - path: appgroups/core/*
  template:
    metadata:
      name: '{{.path.basename}}-{{ index .metadata.labels "cluster-name" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/travismontana/ttl-ops
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{.server}}'
        namespace: core