apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.wildcard.dnsNames }}
    - {{ . }}
  {{- end }}