apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: {{ .Release.Namespace }}
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
spec:
  secretName: wildcard-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ .Values.clusterName }}.{{ .Values.domainName }}"
    - "{{ .Values.clusterName }}.{{ .Values.domainName }}"