apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: {{ .Release.Namespace }}
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ .Values.clusterName }}.tailandtraillabs.org"
    - "{{ .Values.clusterName }}.tailandtraillabs.org"