apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-infra
  namespace: argocd
spec:
  project: default
  destination:
    namespace: k8s-infra
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.signoz.io
    chart: k8s-infra
    targetRevision: 0.15.0
    helm:
      parameters:
      - name: otelCollectorEndpoint
        value: "signoz-otel-collector.signoz.svc:4317"
      - name: otelInsecure
        value: "true"
      - name: presets.otelpExporter.enabled
        value: "true"
      - name: presets.loggingExporter.enabled
        value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true