apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.8.3
    helm:
      parameters:
        - name: api.adminAccount.passwordHash
          # Note: A bcrypt-hashed password will contain `$` characters that
          # MUST each be escaped as `$$`
          value: '$2a$12$9yZhFc8iFUTtmJHdEp9nTuqKC1eZu3I4TritIXF/f9sF73BpskAmK'
        - name: api.adminAccount.tokenSigningKey
          value: 4aN3StktFQyCuSs7xeB4TQCNJNc4549s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
