apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: sabnzbd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/travismontana/ttl-ops
    path: helm/pirateapps
    targetRevision: main
    helm:
      values: |
        name: sabnzbd
        port: 8080
        env:
          HOST_WHITELIST_ENTRIES: "sabnzbd.lab.tailandtraillabs.com"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true