apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: alloy-to-monitoring
  namespace: alloy
spec:
  alloy:
    configMap:
      content: |-
        // Kubernetes discovery
        discovery.kubernetes "nodes" {
          role = "node"
        }
        
        discovery.kubernetes "pods" {
          role = "pod"
        }
        
        discovery.kubernetes "services" {
          role = "service"
        }
        
        // Scrape kubelet cAdvisor metrics (container metrics)
        discovery.relabel "kubelet_cadvisor" {
          targets = discovery.kubernetes.nodes.targets
          
          rule {
            source_labels = ["__meta_kubernetes_node_name"]
            target_label  = "node"
          }
          
          rule {
            source_labels = ["__address__"]
            regex         = "([^:]+)(:[0-9]+)?" 
            replacement   = "$1:10250"
            target_label  = "__address__"
          }
          
          rule {
            replacement  = "/metrics/cadvisor"
            target_label = "__metrics_path__"
          }
        }
        
        prometheus.scrape "kubelet_cadvisor" {
          targets    = discovery.relabel.kubelet_cadvisor.output
          forward_to = [prometheus.relabel.add_cluster.receiver]
          
          scheme = "https"
          bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
          tls_config {
            ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            insecure_skip_verify = false
          }
        }
        
        // Scrape kubelet metrics
        discovery.relabel "kubelet" {
          targets = discovery.kubernetes.nodes.targets
          
          rule {
            source_labels = ["__meta_kubernetes_node_name"]
            target_label  = "node"
          }
          
          rule {
            source_labels = ["__address__"]
            replacement   = "$1:10250"
            target_label  = "__address__"
          }
          
          rule {
            replacement  = "/metrics"
            target_label = "__metrics_path__"
          }
        }
        
        prometheus.scrape "kubelet" {
          targets    = discovery.relabel.kubelet.output
          forward_to = [prometheus.relabel.add_cluster.receiver]
          
          scheme = "https"
          bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
          tls_config {
            ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            insecure_skip_verify = false
          }
        }
        
        // Scrape pods with prometheus.io annotations
        discovery.relabel "pods" {
          targets = discovery.kubernetes.pods.targets
          
          // Only scrape pods with prometheus.io/scrape=true annotation
          rule {
            source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
            action        = "keep"
            regex         = "true"
          }
          
          rule {
            source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
            action        = "replace"
            target_label  = "__metrics_path__"
            regex         = "(.+)"
          }
          
          rule {
            source_labels = ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
            action        = "replace"
            regex         = "([^:]+)(?::\\d+)?;(\\d+)"
            replacement   = "$1:$2"
            target_label  = "__address__"
          }
          
          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            target_label  = "namespace"
          }
          
          rule {
            source_labels = ["__meta_kubernetes_pod_name"]
            target_label  = "pod"
          }
        }
        
        prometheus.scrape "pods" {
          targets    = discovery.relabel.pods.output
          forward_to = [prometheus.relabel.add_cluster.receiver]
        }
        
        // Add cluster label to all metrics
        prometheus.relabel "add_cluster" {
          forward_to = [prometheus.remote_write.local_prom.receiver]
          
          rule {
            target_label = "cluster"
            replacement  = "monitoring"
          }
        }
        
        // Self-monitoring
        prometheus.exporter.self "default" {}
        
        prometheus.scrape "self" {
          targets    = prometheus.exporter.self.default.targets
          forward_to = [prometheus.relabel.add_cluster.receiver]
        }
        
        // Remote write to monitoring cluster
        prometheus.remote_write "local_prom" {
          endpoint {
            url = "http://prometheus.monitoring.abode.tailandtraillabs.org/api/v1/write"
            
            queue_config {
              capacity = 10000
              max_shards = 10
            }
          }
        }