apiVersion: v2
name: immich-stack
description: Immich application stack
type: application
version: 1.0.0
appVersion: "251130-b3068414c"


dependencies:
  - name: immich
    repository: oci://ghcr.io/immich-app/immich-charts/immich    
    version: "*"
