apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bob@bomar.us  # Change this
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: us-east-2 # Change to your region
          accessKeyID: AKIASMOKF2ZWT5DCC644 # Change this
          secretAccessKeySecretRef:
            name: route53-credentials
            key: aws-secret-access-key
