apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.19.0
    helm:
      parameters: []
      values: |
        provider: aws
        aws:
          region: us-east-2
        txtOwnerId: ttl-ops
        domainFilters:
          - tailandtraillabs.com
        policy: sync  # Creates & deletes records
        sources:
          - ingress
          - service
          - traefik-proxy  # For Traefik IngressRoute
        crd:
          create: false  # Traefik CRDs already exist
          apiversion: traefik.io/v1alpha1
          kind: IngressRoute
        interval: 1m
        logLevel: info
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: route53-credentials
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: route53-credentials
                key: aws-secret-access-key
          - name: AWS_REGION
            value: us-east-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true