apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pirateapps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: pirateapps
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/travismontana/ttl-ops.git
    path: applications/
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true